version: '3'
services:
  db:
    image: 'postgres:latest'
    # command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: iot_data_user
    volumes:
      # - ./postgresql.conf:/etc/postgresql.conf
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
